### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by georgiosd** [codekoenig/AspNetCore.Identity.DocumentDb#23]
Hi!

I am getting an ObjectDisposedException after a couple of operations.

Any ideas why?

StackTrace:
```
Exception has occurred: CLR/System.ObjectDisposedException
Exception thrown: 'System.ObjectDisposedException' in Microsoft.Extensions.Identity.Core.dll: 'Cannot access a disposed object.'
   at Microsoft.AspNetCore.Identity.UserManager`1.ThrowIfDisposed()
   at Microsoft.AspNetCore.Identity.UserManager`1.GetUsersInRoleAsync(String roleName)
   at Happenings.Web.Startup.<InitializeUsers>d__8.MoveNext() in 
```

Georgios

**Comment by georgiosd** [comment]
Never mind, I wasn't `Unwrap`ing a nested task.
